from __future__ import annotations

import argparse
import json
import sqlite3
import sys
import tempfile
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from trading_agent.db.schema import create_schema
from trading_agent.ingestion.adjusted_readiness import get_adjusted_ohlc_readiness
from trading_agent.ingestion.reviewed_adjusted_price_evidence import (
    compute_file_sha256,
    run_reviewed_adjusted_price_evidence_intake,
)


DEFAULT_PACKAGE_DIR = Path("tests/fixtures/adjustment_factors/reviewed_evidence_package")
SYMBOLS = ["FPT", "VNM", "VCB"]
TRADE_DATE = "2026-01-02"
RAW_CLOSE = {"FPT": 100.0, "VNM": 200.0, "VCB": 50.0}


def main() -> int:
    parser = argparse.ArgumentParser(description="Run reviewed adjusted-price evidence package QA.")
    parser.add_argument("--package-dir", default=str(DEFAULT_PACKAGE_DIR))
    args = parser.parse_args()

    result = run_package_qa(package_dir=Path(args.package_dir))
    print(json.dumps(result, indent=2, sort_keys=True, ensure_ascii=False))
    return 0 if result["status"] == "ok" else 1


def run_package_qa(*, package_dir: Path) -> dict[str, Any]:
    manifest_path = package_dir / "manifest.json"
    json_payload_path = package_dir / "payload.json"
    csv_payload_path = package_dir / "payload.csv"
    missing = [path.name for path in [manifest_path, json_payload_path, csv_payload_path] if not path.exists()]
    if missing:
        return {
            "status": "invalid_request",
            "package_dir": str(package_dir),
            "reasons": [f"missing_package_files:{','.join(missing)}"],
            "json_dry_run": None,
            "csv_dry_run": None,
            "execute": None,
            "readiness": None,
            "caveats": _caveats(),
        }

    with tempfile.TemporaryDirectory(prefix="vsf_reviewed_package_qa_", ignore_cleanup_errors=True) as temp_dir:
        work_dir = Path(temp_dir)
        json_dry_run = run_reviewed_adjusted_price_evidence_intake(
            manifest_path=manifest_path,
            payload_path=json_payload_path,
            symbols=SYMBOLS,
            validation_output_path=work_dir / "json_validation.json",
            factor_output_path=work_dir / "json_factors.json",
        )

        csv_manifest_path = _write_csv_manifest(manifest_path, csv_payload_path, work_dir)
        csv_dry_run = run_reviewed_adjusted_price_evidence_intake(
            manifest_path=csv_manifest_path,
            payload_path=csv_payload_path,
            symbols=SYMBOLS,
            validation_output_path=work_dir / "csv_validation.json",
            factor_output_path=work_dir / "csv_factors.json",
        )

        db_path = work_dir / "reviewed_package_qa.sqlite"
        _write_daily_price_db(db_path)
        execute = run_reviewed_adjusted_price_evidence_intake(
            manifest_path=manifest_path,
            payload_path=json_payload_path,
            symbols=SYMBOLS,
            validation_output_path=work_dir / "execute_validation.json",
            factor_output_path=work_dir / "execute_factors.json",
            db_path=db_path,
            dry_run=False,
            execute=True,
        )
        readiness = get_adjusted_ohlc_readiness(db_path, symbols=SYMBOLS)

    status = (
        "ok"
        if json_dry_run.get("status") == "ok"
        and csv_dry_run.get("status") == "ok"
        and execute.get("status") == "ok"
        and readiness.get("backtest_gate") == "pass"
        else "not_ready"
    )
    return {
        "status": status,
        "package_dir": str(package_dir),
        "json_dry_run": json_dry_run,
        "csv_dry_run": csv_dry_run,
        "execute": execute,
        "readiness": readiness,
        "caveats": _caveats(),
    }


def _write_csv_manifest(manifest_path: Path, csv_payload_path: Path, work_dir: Path) -> Path:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    manifest["raw_path"] = str(csv_payload_path)
    manifest["payload_sha256"] = compute_file_sha256(csv_payload_path)
    manifest["notes"] = "Temporary CSV manifest generated by package QA from the reviewed package manifest."
    output_path = work_dir / "manifest_csv.json"
    output_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    return output_path


def _write_daily_price_db(path: Path) -> None:
    with sqlite3.connect(path) as con:
        create_schema(con)
        for symbol in SYMBOLS:
            close = RAW_CLOSE[symbol]
            con.execute(
                """
                INSERT INTO daily_prices (
                    security_id, symbol, trade_date, open, high, low, close,
                    volume, value, price_basis, adjustment_status, source_id, raw_path, quality_status
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    f"fixture:reviewed_package:{symbol}:{TRADE_DATE}",
                    symbol,
                    TRADE_DATE,
                    close * 0.95,
                    close * 1.05,
                    close * 0.9,
                    close,
                    1000.0,
                    close * 1000.0,
                    "source_reported",
                    "unknown",
                    "fixture:daily_prices_reviewed_package",
                    f"synthetic://reviewed-evidence-package/{symbol.lower()}",
                    "ok",
                ),
            )
        con.commit()


def _caveats() -> list[str]:
    return [
        "Synthetic reviewed evidence package only; not real market data.",
        "No live fetch, full VN100, production DB mutation, Backtrader, or Docker/scheduler.",
        "Backtrader/VN100 remains blocked until reviewed real evidence and adjusted readiness pass.",
    ]


if __name__ == "__main__":
    raise SystemExit(main())
