import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Conventions',
      items: [{type: 'autogenerated', dirName: 'conventions'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'Data Sources',
      items: [{type: 'autogenerated', dirName: 'data_sources'}],
    },
    {
      type: 'category',
      label: 'Domain Knowledge',
      items: [{type: 'autogenerated', dirName: 'domain_knowledge'}],
    },
    {
      type: 'category',
      label: 'Plans',
      items: [{type: 'autogenerated', dirName: 'plans'}],
    },
    {
      type: 'category',
      label: 'References',
      items: [{type: 'autogenerated', dirName: 'references'}],
    },
    {
      type: 'category',
      label: 'Reports',
      items: [{type: 'autogenerated', dirName: 'reports'}],
    },
    {
      type: 'category',
      label: 'Research Notes',
      items: [{type: 'autogenerated', dirName: 'research_notes/paper_notes'}],
    },
  ],
};

export default sidebars;
